[Desktop Entry]
Name=mytheme
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Ambiance
MetacityTheme=Ambiance
IconTheme=ubuntu-mono-dark
GtkColorScheme=fg_color:#4c4c4c4c4c4c,bg_color:#f2f2f1f1f0f0,text_color:#3c3c3c3c3c3c,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#5f068b22baec,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#000000000000
CursorTheme=DMZ-White
CursorSize=18
ButtonLayout=close,minimize,maximize:
